import type { Metadata } from 'next'
import Slussen from "@/assets/fonts/slussen"
import './globals.css'

export const metadata: Metadata = {
  title: 'Chess',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Slussen.className}>{children}</body>
    </html>
  )
}
